CREATE TABLE USER
(
    ID               BIGINT PRIMARY KEY,
    USERNAME         VARCHAR(32) NOT NULL,
    PASSWORD         VARCHAR(256) NOT NULL,
    PASSWORD_EXPIRED DATE,
    EMAIL            VARCHAR(128),
    NAME             VARCHAR(64) NOT NULL,
    FAMILY_NAME      VARCHAR(64),
    NICKNAME         VARCHAR(64),
    LOCKED           CHAR(1) DEFAULT 'N' NOT NULL,
    DELETED          CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED          TIMESTAMP,
    CREATOR          VARCHAR(32),
    MODIFIED         TIMESTAMP,
    MODIFIER         VARCHAR(32)
);
INSERT INTO USER (ID, USERNAME, PASSWORD, EMAIL, NAME,  PASSWORD_EXPIRED)
VALUES (-1, 'tester', '{noop}test123$', 'tester@test.com', 'foo', ADD_MONTHS(CURRENT_DATE, 3));
INSERT INTO USER (ID, USERNAME, PASSWORD, EMAIL, NAME, PASSWORD_EXPIRED)
VALUES (-2, 'leader', '{noop}lead123$', 'leader@test.com', 'bar', ADD_MONTHS(CURRENT_DATE, 3));



CREATE TABLE AUTHORITY
(
    ID       BIGINT PRIMARY KEY,
    ROLE     VARCHAR(32)         NOT NULL,
    UPPER_ID INT,
    DELETED  CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED  TIMESTAMP,
    CREATOR  VARCHAR(32),
    MODIFIED TIMESTAMP,
    MODIFIER VARCHAR(32)
);

INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-1, 'ADMIN', NULL);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-2, 'MANAGER', -1);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-3, 'INTERN', -2);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-4, 'POST_WRITE', -3);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-5, 'POST_READ', -3);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-6, 'POST_REMOVE', -4);

CREATE TABLE USER_AUTHORITY
(
    ID           BIGINT PRIMARY KEY,
    USER_ID      BIGINT              NOT NULL,
    AUTHORITY_ID BIGINT              NOT NULL,
    DELETED      CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED      TIMESTAMP,
    CREATOR      VARCHAR(32),
    MODIFIED     TIMESTAMP,
    MODIFIER     VARCHAR(32)
);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID)
VALUES (-1, -1, -2);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID)
VALUES (-2, -1, -6);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID)
VALUES (-3, -2, -4);
