CREATE TABLE USER
(
    ID       INT PRIMARY KEY,
    USERNAME VARCHAR(32),
    PASSWORD VARCHAR(256),
    EMAIL VARCHAR(128),
    PASSWORD_EXPIRED DATE,
    LOCKED CHAR(1) DEFAULT 'N' NOT NULL,
    DELETED  CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED  TIMESTAMP,
    CREATOR  VARCHAR(32),
    MODIFIED TIMESTAMP,
    MODIFIER VARCHAR(32)
);
INSERT INTO USER (ID, USERNAME, PASSWORD, EMAIL, PASSWORD_EXPIRED)
VALUES (-1, 'tester', '{noop}test123$', 'tester@test.com', ADD_MONTHS(CURRENT_DATE, 3));
INSERT INTO USER (ID, USERNAME, PASSWORD, EMAIL, PASSWORD_EXPIRED)
VALUES (-2, 'leader', '{noop}lead123$', 'leader@test.com', ADD_MONTHS(CURRENT_DATE, 3));



CREATE TABLE AUTHORITY
(
    ID       INT PRIMARY KEY,
    ROLE     VARCHAR(32) UNIQUE NOT NULL,
    UPPER_ID INT,
    DELETED  CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED  TIMESTAMP,
    CREATOR  VARCHAR(32),
    MODIFIED TIMESTAMP,
    MODIFIER VARCHAR(32)
);

INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-1, 'ADMIN', NULL);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-2, 'MANAGER', -1);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-3, 'INTERN', -2);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-4, 'POST_WRITE', -1);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-5, 'POST_READ', -1);
INSERT INTO AUTHORITY (ID, ROLE, UPPER_ID)
VALUES (-6, 'POST_REMOVE', -1);

CREATE TABLE USER_AUTHORITY
(
    ID           INT PRIMARY KEY,
    USER_ID      INT NOT NULL,
    AUTHORITY_ID INT NOT NULL,
    DELETED      CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED      TIMESTAMP,
    CREATOR      VARCHAR(32),
    MODIFIED     TIMESTAMP,
    MODIFIER     VARCHAR(32),
    UNIQUE (USER_ID, AUTHORITY_ID)
);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID)
VALUES (-1, -1, -3);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID)
VALUES (-2, -1, -4);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID)
VALUES (-3, -2, -4);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID)
VALUES (-4, -2, -5);
