spring:
  messages:
    cache-duration: 3
  data:
    web:
      pageable:
        default-page-size: 5
  sql:
    init:
      schema-locations:
        - "classpath:db/schema-data-h2.sql"
  jpa:
    hibernate:
      ddl-auto: update

logging:
  pattern:
    console: "%highlight(%-5level) %d{HH:mm:ss.SSS}[%green(%thread)]%magenta(%logger{36}) %msg %n"
